services:
  rust-genai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8082:8082"
    env_file:
    - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
